# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be

include: package:flutter_lints/flutter.yaml

linter:
  # https://dart-lang.github.io/linter/lints/index.html.
  rules:
    avoid_print: false
    prefer_single_quotes: true
    file_names: true
    avoid_empty_else: true
    avoid_dynamic_calls: false
    avoid_returning_null_for_future: true
    avoid_type_to_string: true
    avoid_types_as_parameter_names: true
    close_sinks: true
    empty_statements: true
    hash_and_equals: true
    avoid_null_checks_in_equality_operators: true
    sort_pub_dependencies: true
    use_raw_strings: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
