name: interview
description: Interview Project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter

  flutter_color: any
  flutter_native_splash: any
  http: ^0.13.4
  provider: ^6.0.2
  wakelock: any


dev_dependencies:
  async: ^2.8.2
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/SplashBg.png